In [1]:
import pandas as pd

In [4]:
df=pd.read_excel(r'C:\Users\DELL\Desktop\Data\Tech_Products_Sales_Data.xlsx')

In [5]:
df.head()

,Transaction ID,Product,Quantity,Unit Price (INR),Date,Customer Name,State,Country,Sales Channel,Payment Type,Sales
0,TX0001,Smartwatch,9,8941,2024-04-12,Vivaan Sastry,Arunachal Pradesh,India,Store,Credit Card,80469
1,TX0002,Desktop PC,9,19827,2024-02-06,Ishaan Madan,Odisha,India,Store,Credit Card,178443
2,TX0003,Desktop PC,4,16640,2023-12-16,Azad Sandhu,Bihar,India,Online,Credit Card,66560
3,TX0004,E-Reader,3,2945,2024-09-11,Shray Chawla,Manipur,India,Online,Credit Card,8835
4,TX0005,Laptop,4,2848,2023-10-24,Zara Kata,Madhya Pradesh,India,Direct,Net Banking,11392

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   str
 1   Product           1000 non-null   str
 2   Quantity          1000 non-null   int64
 3   Unit Price (INR)  1000 non-null   int64
 4   Date              1000 non-null   str
 5   Customer Name     1000 non-null   str
 6   State             1000 non-null   str
 7   Country           1000 non-null   str
 8   Sales Channel     1000 non-null   str
 9   Payment Type      1000 non-null   str
 10  Sales             1000 non-null   int64
dtypes: int64(3), str(8)
memory usage: 149.1 KB

In [7]:
df.describe()

          Quantity  Unit Price (INR)         Sales
count  1000.000000       1000.000000    1000.00000
mean      4.899000      10509.633000   51202.11700
std       2.540719       5241.520851   38852.61529
min       1.000000       2040.000000    2043.00000
25%       3.000000       5962.000000   20152.50000
50%       5.000000      10208.000000   39636.50000
75%       7.000000      14846.000000   74091.00000
max       9.000000      19994.000000  178443.00000

In [8]:
df.describe(include='all')

,Transaction ID,Product,Quantity,Unit Price (INR),Date,Customer Name,State,Country,Sales Channel,Payment Type,Sales
count,1000,1000,1000.000000,1000.000000,1000,1000,1000,1000,1000,1000,1000.00000
unique,1000,10,NaN,NaN,334,996,28,1,3,5,NaN
top,TX0001,Printer,NaN,NaN,2024-04-18,Eshani Kari,Manipur,India,Store,Cash,NaN
freq,1,113,NaN,NaN,8,2,45,1000,346,225,NaN
mean,NaN,NaN,4.899000,10509.633000,NaN,NaN,NaN,NaN,NaN,NaN,51202.11700
std,NaN,NaN,2.540719,5241.520851,NaN,NaN,NaN,NaN,NaN,NaN,38852.61529
min,NaN,NaN,1.000000,2040.000000,NaN,NaN,NaN,NaN,NaN,NaN,2043.00000
25%,NaN,NaN,3.000000,5962.000000,NaN,NaN,NaN,NaN,NaN,NaN,20152.50000
50%,NaN,NaN,5.000000,10208.000000,NaN,NaN,NaN,NaN,NaN,NaN,39636.50000
75%,NaN,NaN,7.000000,14846.000000,NaN,NaN,NaN,NaN,NaN,NaN,74091.00000
max,NaN,NaN,9.000000,19994.000000,NaN,NaN,NaN,NaN,NaN,NaN,178443.00000

In [9]:
df.isnull().sum()

Transaction ID      0
Product             0
Quantity            0
Unit Price (INR)    0
Date                0
Customer Name       0
State               0
Country             0
Sales Channel       0
Payment Type        0
Sales               0
dtype: int64

In [12]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [13]:
df.columns

Index(['Transaction ID', 'Product', 'Quantity', 'Unit Price (INR)', 'Date',
       'Customer Name', 'State', 'Country', 'Sales Channel', 'Payment Type',
       'Sales'],
      dtype='str')

In [16]:
df.columns=df.columns.str.replace(' ','_')

In [17]:
df.columns

Index(['Transaction_ID', 'Product', 'Quantity', 'Unit_Price_(INR)', 'Date',
       'Customer_Name', 'State', 'Country', 'Sales_Channel', 'Payment_Type',
       'Sales'],
      dtype='str')

In [18]:
df=df.rename(columns={'Unit_Price_(INR)':'Unit_Price'})

In [19]:
df.columns

Index(['Transaction_ID', 'Product', 'Quantity', 'Unit_Price', 'Date',
       'Customer_Name', 'State', 'Country', 'Sales_Channel', 'Payment_Type',
       'Sales'],
      dtype='str')

In [20]:
df

,Transaction_ID,Product,Quantity,Unit_Price,Date,Customer_Name,State,Country,Sales_Channel,Payment_Type,Sales
0,TX0001,Smartwatch,9,8941,2024-04-12,Vivaan Sastry,Arunachal Pradesh,India,Store,Credit Card,80469
1,TX0002,Desktop PC,9,19827,2024-02-06,Ishaan Madan,Odisha,India,Store,Credit Card,178443
2,TX0003,Desktop PC,4,16640,2023-12-16,Azad Sandhu,Bihar,India,Online,Credit Card,66560
3,TX0004,E-Reader,3,2945,2024-09-11,Shray Chawla,Manipur,India,Online,Credit Card,8835
4,TX0005,Laptop,4,2848,2023-10-24,Zara Kata,Madhya Pradesh,India,Direct,Net Banking,11392
...,...,...,...,...,...,...,...,...,...,...,...
995,TX0996,Desktop PC,3,16668,2024-03-02,Trisha Doctor,Karnataka,India,Store,Cash,50004
996,TX0997,Printer,9,7752,2024-08-20,Kartik Gola,Telangana,India,Store,Debit Card,69768
997,TX0998,Camera,8,6466,2024-06-23,Rhea Thaker,Jharkhand,India,Online,UPI,51728
998,TX0999,Tablet,4,6409,2023-11-27,Tejas Dhar,Odisha,India,Store,Credit Card,25636
999,TX1000,Tablet,8,2524,2023-12-04,Shaan Char,Odisha,India,Store,Net Banking,20192

In [21]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in .\anaconda3\New folder\Lib\site-packages (1.2.3)
Requirement already satisfied: sqlalchemy in .\anaconda3\New folder\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in .\anaconda3\New folder\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in .\anaconda3\New folder\Lib\site-packages (from sqlalchemy) (4.16.0)

In [23]:
from sqlalchemy import create_engine, URL

In [24]:
connection_url = URL.create(
    drivername="mysql+pymysql",
    username="root",
    password="Pass@123",
    host="localhost",
    port=3306,
    database="Tech_Products_Sales_Data"
)

engine = create_engine(connection_url)

In [25]:
table_name="salesdata"
df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

1000

In [27]:
df=pd.read_sql("select * from salesdata limit 5;", engine)

In [28]:
df

,Transaction_ID,Product,Quantity,Unit_Price,Date,Customer_Name,State,Country,Sales_Channel,Payment_Type,Sales
0,TX0001,Smartwatch,9,8941,2024-04-12,Vivaan Sastry,Arunachal Pradesh,India,Store,Credit Card,80469
1,TX0002,Desktop PC,9,19827,2024-02-06,Ishaan Madan,Odisha,India,Store,Credit Card,178443
2,TX0003,Desktop PC,4,16640,2023-12-16,Azad Sandhu,Bihar,India,Online,Credit Card,66560
3,TX0004,E-Reader,3,2945,2024-09-11,Shray Chawla,Manipur,India,Online,Credit Card,8835
4,TX0005,Laptop,4,2848,2023-10-24,Zara Kata,Madhya Pradesh,India,Direct,Net Banking,11392